### ISSUE TITLE
don't call home to newrelic

### ISSUE THREAD

**Issue by homeyer** [waffleio/waffle.io-takeout#41]
customer reported, not sure which service is doing it.

**Comment by danrschlosser** [comment]
Hey @homeyer,

We're running into some problems that might be related to this.  When we startup the app, it fails, and running

```bash
docker logs waffle-app
```

is yielding a newrelic error:

```
WARNING: Superstack logging enabled, may see increased memory usage.
project root: /src
adding CA certs from /etc/waffle/ca-certificates
connected to mongo at mongodb://mongo
newrelic.noticeError (dev): server domain error: TypeError: Cannot read property 'clientId' of null
    at /src/server/gen/auth/passport.js:60:37
    at /src/node_modules/q/q.js:1142:26
    at _fulfilled (/src/node_modules/q/q.js:787:54)
    at self.promiseDispatch.done (/src/node_modules/q/q.js:816:30)
    at Promise.promise.promiseDispatch (/src/node_modules/q/q.js:749:13)
    at /src/node_modules/q/q.js:509:49
    at flush (/src/node_modules/q/q.js:108:17)
    at process._tickDomainCallback (node.js:463:13)
    at requestTick (/src/node_modules/q/q.js:164:21)
    at nextTick (/src/node_modules/q/q.js:154:13)
    at /src/node_modules/q/q.js:556:13
    at Array.reduce (native)
    at /src/node_modules/q/q.js:221:21
    at become (/src/node_modules/q/q.js:555:9)
    at deferred.resolve (/src/node_modules/q/q.js:571:9)
    at Promise.<anonymous> (/src/node_modules/q/q.js:616:18)
    at Promise.on (/src/node_modules/@waffleio/waffle.io-models/node_modules/mongoose/node_modules/mpromise/lib/promise.js:61:31)
    at Promise.onResolve (/src/node_modules/@waffleio/waffle.io-models/node_modules/mongoose/node_modules/mpromise/lib/promise.js:175:8)
    at Promise (/src/node_modules/@waffleio/waffle.io-models/node_modules/mongoose/node_modules/mpromise/lib/promise.js:30:10)
    at new Promise (/src/node_modules/@waffleio/waffle.io-models/node_modules/mongoose/lib/promise.js:26:12)
    at Query.findOne (/src/node_modules/@waffleio/waffle.io-models/node_modules/mongoose/lib/query.js:1129:17)
    at Function.findOne (/src/node_modules/@waffleio/waffle.io-models/node_modules/mongoose/lib/model.js:1060:13)
    at Function.DBObject.findOne (/src/node_modules/@waffleio/waffle.io-models/lib/models/db-object.js:49:42)
    at Promise.post (/src/node_modules/q/q.js:1074:36)
    at requestTick (/src/node_modules/q/q.js:164:21)
    at nextTick (/src/node_modules/q/q.js:154:13)
    at Promise.dispatch (/src/node_modules/q/q.js:1303:5)
    at Function.Q.nsend.Q.nmcall.Q.ninvoke (/src/node_modules/q/q.js:1854:15)
    at Function.Passport.initialize (/src/server/gen/auth/passport.js:50:11)
    at module.exports (/src/server/gen/app.js:19:21)
    at /src/server/gen/server.js:63:32
    at LOOP (fs.js:1369:14)
```

Any workarounds here?

**Comment by homeyer** [comment]
Hmm, looks like the migrations might not have run. Can you check the docker logs for the waffle.io-migrations container?

**Comment by homeyer** [comment]
(the `newrelic.noticeError` is just a console.log, we have it mocked out like that so we can still see errors in the logs locally)

**Comment by danrschlosser** [comment]
That worked!

We're now getting `docker logs waffle-hedwig` issues:

```
Error { type: 'WebSocketError',
  error: 'Unknown socket error: ENOTFOUND getaddrinfo' }
newrelic.noticeError (dev): Connection Error: { type: 'WebSocketError',
  error: 'Unknown socket error: ENOTFOUND getaddrinfo' }
delaying 1 second(s) before connecting...
State changed from disconnected to connecting.
State changed from connecting to disconnected.
Error { type: 'WebSocketError',
  error: 'Unknown socket error: ENOTFOUND getaddrinfo' }
newrelic.noticeError (dev): Connection Error: { type: 'WebSocketError',
  error: 'Unknown socket error: ENOTFOUND getaddrinfo' }
delaying 1 second(s) before connecting...
State changed from disconnected to connecting.
State changed from connecting to disconnected.
Error { type: 'WebSocketError',
  error: 'Unknown socket error: ENOTFOUND getaddrinfo' }
newrelic.noticeError (dev): Connection Error: { type: 'WebSocketError',
  error: 'Unknown socket error: ENOTFOUND getaddrinfo' }
delaying 1 second(s) before connecting...
State changed from disconnected to connecting.
State changed from connecting to disconnected.
```

**Comment by homeyer** [comment]
Looks like it can't find `poxa`, our realtime service. Did you [create the DNS entries](https://github.com/waffleio/waffle.io-takeout/blob/master/doc/INSTALL.md#prerequisites)?

**Comment by homeyer** [comment]
Added a fix for newrelic calling home - our debug logs say `newrelic`, but it's stubbed out in every takeout environment. Changed stubs to not say `newrelic` and changed newrelic inclusion to log when it's added, so it's clear when it's enabled.

This will be included in the next release of takeout.
